// solid/src/App.tsx
import type { Component } from 'solid-js'
import { Takt, useTakt } from '@vskstudio/takt-solid'

const BuyButton: Component = () => {
  // never-throwing no-op until <Takt> has mounted
  const takt = useTakt()

  const buy = () =>
    takt.track('Purchase', {
      props: { plan: 'pro' },
      revenue: { amount: '29.00', currency: 'EUR' },
    })

  return <button onClick={buy}>Buy pro</button>
}

const App: Component = () => (
  // domain + default /api/event endpoint; <Takt> fires the initial pageview.
  // excludeLocalhost={false} so events fire during local dev.
  // scriptOrigin="https://stats.example.com" : sert le tracker depuis votre domaine (first-party / anti-adblock)
  <Takt domain="example.com" endpoint="/api/event" track404 excludeLocalhost={false}>
    <main>
      <h1>Takt + SolidJS</h1>
      <BuyButton />
    </main>
  </Takt>
)

export default App

// react/src/App.tsx
import { Takt, TaktEvent, useTakt, useTaktEvent } from '@vskstudio/takt-react'

// <Takt> mounts the analytics instance, fires the initial pageview, and
// (with spa) tracks SPA navigations automatically. excludeLocalhost is
// disabled here so events are emitted during local development.
export default function App() {
  return (
    // scriptOrigin="https://stats.example.com" : sert le tracker depuis votre domaine (first-party / anti-adblock)
    <Takt domain="example.com" endpoint="/api/event" outbound files spa track404 excludeLocalhost={false}>
      <main>
        <h1>Takt React Example</h1>
        <BuyButton />
        <SignupButton />
      </main>
    </Takt>
  )
}

// Imperative tracking via the hook: a click with props + revenue.
function BuyButton() {
  const takt = useTakt()
  return (
    <button
      onClick={() =>
        takt.track('Buy', {
          props: { plan: 'pro', source: 'hero' },
          revenue: { amount: '29.00', currency: 'EUR' },
        })
      }
    >
      Buy pro
    </button>
  )
}

// Declarative tracking: useTaktEvent returns onClick to spread, and
// <TaktEvent> wraps a child element.
function SignupButton() {
  const onSignup = useTaktEvent({ name: 'Signup', props: { plan: 'free' } })
  return (
    <>
      <button {...onSignup}>Sign up</button>
      <TaktEvent name="Contact" props={{ channel: 'footer' }}>
        <button>Contact</button>
      </TaktEvent>
    </>
  )
}
