// solid/src/App.tsx
import type { Component } from 'solid-js'
import { Takt, useTakt } from '@vskstudio/takt-solid'

const BuyButton: Component = () => {
  // never-throwing no-op until <Takt> has mounted
  const takt = useTakt()

  const buy = () =>
    takt.track('Purchase', {
      props: { plan: 'pro' },
      revenue: { amount: '29.00', currency: 'EUR' },
    })

  return <button onClick={buy}>Buy pro</button>
}

const App: Component = () => (
  // domain + default /api/event endpoint; <Takt> fires the initial pageview.
  // excludeLocalhost={false} so events fire during local dev.
  // scriptOrigin="https://stats.example.com" : sert le tracker depuis votre domaine (first-party / anti-adblock)
  <Takt domain="example.com" endpoint="/api/event" track404 excludeLocalhost={false}>
    <main>
      <h1>Takt + SolidJS</h1>
      <BuyButton />
    </main>
  </Takt>
)

export default App

// svelte/src/App.svelte
<script lang="ts">
  import { Takt, useTakt } from '@vskstudio/takt-svelte'

  const takt = useTakt()

  function buy() {
    takt.track('Purchase', {
      props: { plan: 'pro', source: 'example' },
      revenue: { amount: '29.00', currency: 'EUR' },
    })
  }
</script>

<!-- Boots core, fires the initial pageview, wires SPA nav. -->
<!-- scriptOrigin="https://stats.example.com" : sert le tracker depuis votre domaine (first-party / anti-adblock) -->
<Takt domain="example.com" endpoint="/api/event" track404 excludeLocalhost={false} />

<main>
  <h1>Takt + Svelte 5</h1>
  <p>An initial pageview is sent automatically on mount.</p>
  <button onclick={buy}>Buy pro (track Purchase + revenue)</button>
  <button onclick={() => takt.pageview()}>Send pageview</button>
</main>
